In [3]:
def sigma(x):
    ret = 0
    for x_i in x:
        ret += x_i
    return ret

x = [i + 1 for i in range(100)]

print(sigma(x))

5050


In [4]:
def product(x):
    ret = 1
    for x_i in x:
        ret *= x_i
    return ret

x = [i + 1 for i in range(100)]

print(product(x))

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000


#  수학 기호

### max 함수
인자로 들어온 숫자 중에서 가장 큰 값을 골라 반환하는 것을 말한다.
### argmax 함수
인자로 대상함수와 함수의 입력 셋을 받게 된다. 다음 수식에서 대상함수는 f가 되고, 입력 셋은 x 포함관계가 된다 .


In [6]:
import numpy as np

def argmax(target_func,X):
    max_val = -np.inf
    ret = None
    for x in X:
        val = f(x)
        if val > max_val:
            max_val = val
            ret = X

    return ret

def f(x):
    return -np.log(x)

print(argmax(f,x))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


# 파이토치를 사용해서 탠서 생성

In [1]:
import torch
# 실수형으로 생성
ft = torch.FloatTensor([[1,2],
                        [3,4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [2]:
lt = torch.LongTensor([[1,2],
                       [3,4]])
lt

tensor([[1, 2],
        [3, 4]])

In [4]:
bt = torch.ByteTensor([[1,0],
                       [0,1]])
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [5]:
x = torch.FloatTensor(3,2)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## 넘파이 호환

In [6]:
import numpy as np
x = np.array([[1,2],
              [3,4]]) # 넘 파이로 배열 생성

print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [7]:
# 넘파이로 생성한 걸 파이토치 텐서로 변환하기

x = torch.from_numpy(x)
x

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [9]:
# 반대로 텐서를 넘파이로 변환도 가능하다
x = x.numpy()
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


## 텐서 타입 변환

In [13]:
ft.long()



tensor([[1, 2],
        [3, 4]])

In [14]:
lt.float()


tensor([[1., 2.],
        [3., 4.]])

## 텐서 크키 구하기

In [15]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       [[5,6],
                        [7,8]],
                       [[9,10],
                        [11,12]]])

In [18]:
print(x.size())
print(x.shape)

# 텐서를 구하려면 size()함수결과값이 shape 속성에 담겨있다고생각하면됨

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [19]:
print(x.size(1))
print(x.shape[1])

2
2


In [20]:
# 만일 음수를 넣어주면 뒤에서부터의 순서에 해당합니다
print(x.size(-1))
print(x.shape[-1])

2
2


In [21]:
# 만약 텐서의 차원의 개수를 알기위해서는 dim()함수를 사용합니다

print(x.dim())
print(len(x.size()))

3
3
