# 기본 연산 - 실습

In [3]:
import torch

a = torch.FloatTensor([[1,2],
                       [3,4]])
b = torch.FloatTensor([[2,2],
                       [3,3]])


## 요소별 산술 연산

In [4]:
#덧셈
a + b

tensor([[3., 4.],
        [6., 7.]])

In [5]:
# 뺄셈
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [6]:
# 나눗셈
a / b

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])

In [7]:
# 제곱연산

a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

In [8]:
# 논리 연산(==)

a == b

tensor([[False,  True],
        [ True, False]])

In [9]:
# 논리 연산 (!=)
a != b

tensor([[ True, False],
        [False,  True]])

## 인플레이스 연산
앞에서 수행한 연산들의 결과 텐서는 메모리에 새롭게 활당됩니다.
빈메모리에 저장되고 텐서 결과 값이 출력되는겁니다.

하지만 지금 부터는 설명할 인플레이스 연산은 같은 연산을 수행하지만 결과값이 기존 텐서에 저장되는 **차이점**이 있습니다.

In [10]:
print(a)
print(b)

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 2.],
        [3., 3.]])


In [11]:
print(a.mul(b)) # 연산은 a * b 와 같은 연산입니다. 
#연산결과는 새로운 메모리에 활당됩니다. 따라서 a를 출력하면 그대로인것을 볼수있습니다.

print(a)
print(b)

tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 2.],
        [3., 3.]])


In [12]:
# 인플레이스 연산들은 밑줄이 함수명 뒤에 붙어있는 것이 특징입니다.
# 따라서 곱셈 함수의 인플레이스 연산 함수는 mul_()입니다.
print(a.mul_(b)) 
print(a) # 결과 값이 a에 저장되는 것을 볼수있음
print(b)

# 새로운 공간에 만들어서 저장하는것이 아닌 기존의 공간에 저장하므로 효율적일것같지만
# 파이토치 측에서는 컬렉터가 호율적으로 작동하기에 굳이 인플레이스 연산을 사용할 필요는 없다고함

tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[2., 2.],
        [3., 3.]])


## 차원 축소 연산 : 합과 평균

In [13]:
x = torch.FloatTensor([[1,2],
                       [3,4]])


In [14]:
print(x.sum())
# sum() 통해 합을 구할수있음

tensor(10.)


In [15]:
print(x.mean())
# mean()통해 평균값을 구할수있음

tensor(2.5000)


행렬의 전체 합이나 평균은 텐서나 행렬이 아닌 스칼라 값으로 저장되므로 차원이 축소된다고 볼 수 있음

In [16]:
# 여기 함수에 dim() 인자에 원하는 연산의 차원을 넣어줄수 있다.
# 간단하게 dim() 인자의 값은 없어지는 차워이라고 생각하면 쉽다.

print(x.sum(dim=0))
# dim()인자는 -1로도 줄수있는데 뒤에서 첫번째 값을 의미한다.
print(x.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])


## 브로드캐스트 연산

### 탠서 + 스칼라

In [17]:
x = torch.FloatTensor([[1,2],
                       [3,4]])
y = 1
z = x + y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


### 텐서 + 백터
- 차원 수만 맞춰 주면 계산이 가능하다 예를 들어 3차원 과 1차원 의 계산일 경우 
- 1차원을 3차원으로 강제로 늘려준다 그리고 계산을 한다 차원 만 맞으면 계산이 가능하니까 

In [18]:
x = torch.FloatTensor([[1,2],
                       [3,4]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

z = x + y
print(z)
print(z.size())

torch.Size([2, 2])
torch.Size([2])
tensor([[4., 7.],
        [6., 9.]])
torch.Size([2, 2])


In [19]:
x = torch.FloatTensor([[[1,2]]])
y = torch.FloatTensor([3,
                       5])

print(x.size())
print(y.size())

z = x + y
print(z)
print(z.size())

torch.Size([1, 1, 2])
torch.Size([2])
tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


### 텐서 + 텐서

In [20]:
x = torch.FloatTensor([[1,2]])
y = torch.FloatTensor([[3],
                       [5]])

print(x.size())
print(y.size())

z = x + y
print(z)
print(z.size())

torch.Size([1, 2])
torch.Size([2, 1])
tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


# 텐서 형태 변환
## View 함수

In [21]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       [[5,6],
                        [7,8]],
                       [[9,10],
                        [11,12]]])

print(x.size())

torch.Size([3, 2, 2])


In [22]:
print(x.view(12))
print(x.view(3,4))
print(x.view(3,1,4))


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [23]:
#만약 새로운 크기가 기존 텐서의 요소 개수와 맞지 않으면 오류가 발생하게 됩니다. 
#하지만, view함수에 -1을 활용하면 일일 이 요소 갯수를 맞추기 위해 노력할 필요 없음
# -1이 들어간 차원의 크기는 다른 차원의 값들을 곱하고 남은 필요한 값이 자동으로 채워집니다.
print(x.view(-1)) 
print(x.view(3,-1))
print(x.view(-1,1,3))

#결론 -1로 채우면 알아서 채워준다.

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.]],

        [[ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.]],

        [[10., 11., 12.]]])


In [24]:
y = x.view(3,4)
x.storage().data_ptr() == y.storage().data_ptr()
#view 함수의 결과 텐서 주소는 바뀌지 않는다. 따라서 다음 코드에서 y의 값을 변경할시
#x값도 같이 변하게 됨

C:\Users\tgv99\AppData\Local\Temp\ipykernel_6664\485452161.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x.storage().data_ptr() == y.storage().data_ptr()


True

##### View 함수
- view 함수는 메모리에 순차대로 선언된 텐서에서만 작동한다. 만약 이를 어길시 오류를 발생하게된다. 
- 오류가 발생시 contiguous 함수를 호출한뒤 view 함수를 호출하면 된다.

##### coniguous 함수
- coniguous함수를 사용하면 메모리에 새롭게 활당을 안한 상태로 결과값을 반환한다.

##### reshape 함수
- view함수와 동일하게 동작하되 congiuous 함수와 view함수를 순차적으로 후출한것과 동일하다.


In [25]:
print(x.reshape(3,4))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


## Squeeze 함수
- 함수 차원의 크기가 1인 모든 차원을 없애는 역활을 한다.
- 매개 변수로 숫자가 들어갈수있으며, 숫자들은 인덱스 위치를 나타낸다.

In [26]:
x = torch.FloatTensor([[[1,2],
                        [3,4]]])
print(x.size())
# Squeeze 함수는 차원의 크기가 1인차원을 없애주는 역활을 한다.

torch.Size([1, 2, 2])


In [27]:
print(x.squeeze())
print(x.squeeze().size())

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


In [28]:
# 매개변수로 숫자가 들어갈수있고 그숫자는 인덱스 위치를 나타낸다.
print(x.squeeze(0).size())
print(x.squeeze(1).size())

torch.Size([2, 2])
torch.Size([1, 2, 2])


## Unsqueeze 함수
- Unsqueeze는 지정된 차원의 인덱스에 차원의 크기가 1인 차워을 삽입합니다.

In [29]:
x = torch.FloatTensor([[1,2],
                       [3,4]])
print(x.size())

torch.Size([2, 2])


In [30]:
print(x.unsqueeze(1).size())
print(x.unsqueeze(-1).size())
print(x.unsqueeze(2).size())

torch.Size([2, 1, 2])
torch.Size([2, 2, 1])
torch.Size([2, 2, 1])


In [31]:
# reshape를 통해서 구할수있다.
print(x.reshape(2,2,-1).size())

torch.Size([2, 2, 1])


# 텐서 자르기 & 붙이기

In [32]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       [[5,6],
                        [7,8]],
                       [[9,10],
                        [11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [33]:
print(x[0])
# 주의 할점은 첫번째 차원은 잘라내는 과정에서 사라졌다는것.
# 즉 3*2*2이지만 2*2크기의 행렬만남음

tensor([[1., 2.],
        [3., 4.]])


In [34]:
# 음수를 넣어서 뒤에서 접근하는방법도 가능
print(x[-1])

tensor([[ 9., 10.],
        [11., 12.]])


In [35]:
# 첫번째 차원이 아닌 중간차원에 대해서 작업을 수행하고 싶을 경우콜론(:)기호를 사용하면 된다.
# 배열에서 
print(x[:,0])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


In [36]:
print(x[1:2,1:,:].size())


torch.Size([1, 1, 2])


## Split 함수
- Split 함수는 텐서를 특정 차원에 대해서 원하는 크기로 잘라줍니다. 
- 다음 코드는 Split함수를 통해 첫 번째 차워의 크기가 4가 되도록 텐서를 등분한 후에 각각의 등분된 텐서 크기를 출력하는 코드

In [37]:
x = torch.FloatTensor(10,4)
splits = x.split(4,dim=0)
for s in splits:
    print(s.size())

# 10개를 4개씩 나눌경우 나머지 2개된다 그래서 마지막에는 크키가 [2,4]로 출력된다.

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


## Chunk함수  
- split 함수는 개수에 상관 없이 원하는 크기로 나누었다면 크기에 상관없이 원하는 개수로 나누는 chunk 함수

In [38]:
#3등분 하는코드
x = torch.FloatTensor(8,4)
chunks = x.chunk(3,dim=0)
for c in chunks:
    print(c.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


## Index Select 함수

In [39]:
x = torch.FloatTensor([[[1,1],
                        [2,2]],
                       [[3,3],
                        [4,4]],
                       [[5,5],
                        [6,6]]])
indice = torch.LongTensor([2,1])
print(x.size())

torch.Size([3, 2, 2])


In [40]:
y = x.index_select(dim = 0,index = indice)
print(y)
print(y.size())

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


## Concatenate 함수
- 텐서를 서로 합쳐서 하나의 텐서로 만드는 함수
- 하나로 합칠때 배열내의 두개 이상의 텐서를 합쳐서 하나로 변환
- 합쳐질때 다른차원의 크기가 같아야함

In [41]:
x = torch.FloatTensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
y = torch.FloatTensor([[10,11,12],
                       [13,14,15],
                       [16,17,18]])

print(x.size(),y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [42]:
# 하나로 합치는함수
# dim = 0 은 세로로 두텐서를 붙라는 코드임

z = torch.cat([x,y],dim=0)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])


In [43]:
# dim =-1 로 줄경우 가로로 붙는다
z = torch.cat([x,y],dim=-1)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


In [44]:
z = torch.cat([x,y],dim=1)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


## 3차원 텐서의 경우
### 새로운 3차원 x 텐서 정의
x_new = torch.FloatTensor([[[1, 2, 3], [4, 5, 6]]])  # Size: [1, 2, 3]
### 새로운 3차원 y 텐서 정의
y_new = torch.FloatTensor([[[7, 8, 9], [10, 11, 12]]])  # Size: [1, 2, 3]

### dim=0으로 연결한 경우
```
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])
Size: [2, 2, 3]
```
### dim=1으로 연결한 경우:
```
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]])
Size: [1, 4, 3]
```
### dim=2으로 연결한 경우:
```
tensor([[[ 1.,  2.,  3.,  7.,  8.,  9.],
         [ 4.,  5.,  6., 10., 11., 12.]]])
Size: [1, 2, 6]
```

## stack 함수
- 붙이는 작업이 아닌 쌓기 작업을 수행
- cat 과 달리 사이즈가 달라도 상관없음
- stack 함수는 새로운 차워을 만든뒤에 cat 함수를 수행한것과 동일하다.

In [45]:
print(f"x 텐서:\n{x}")
print(f"x 텐서:\n{x.size()}")
print(f"y 텐서:\n{y}")
print(f"y 텐서:\n{y.size()}")
z = torch.stack([x,y])
print(z)
print(z.size())

x 텐서:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
x 텐서:
torch.Size([3, 3])
y 텐서:
tensor([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
y 텐서:
torch.Size([3, 3])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


In [46]:
z = torch.stack([x,y],dim = -1)
print(z)
print(z.size())

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])


## 3차원 텐서의 경우
### 새로운 3차원 x 텐서 정의
x_stack = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Size: [2, 2, 2]
### 새로운 3차원 y 텐서 정의
y_stack = torch.FloatTensor([[[9, 10, 11], [12, 13, 14]]])  # Size: [1, 2, 3]

### dim=0으로 연결한 경우:
```
 tensor([[[[ 1.,  2.],
          [ 3.,  4.]],

         [[ 5.,  6.],
          [ 7.,  8.]]],


        [[[ 9., 10., 11.],
          [12., 13., 14.]],

         [[ 9., 10., 11.],
          [12., 13., 14.]]]])
Size of stacked z with dim=0: torch.Size([2, 2, 2, 3])
``` 
### dim=1으로 연결한 경우:
```
 tensor([[[[ 1.,  2.],
          [ 3.,  4.]],

         [[ 9., 10., 11.],
          [12., 13., 14.]]],


        [[[ 5.,  6.],
          [ 7.,  8.]],

         [[ 9., 10., 11.],
          [12., 13., 14.]]]])
Size of stacked z with dim=1: torch.Size([2, 2, 2, 3])

```
### dim=2으로 연결한 경우:
```
 tensor([[[[ 1.,  9., 10., 11.],
          [ 2.,  9., 10., 11.]],

         [[ 3., 12., 13., 14.],
          [ 4., 12., 13., 14.]]],


        [[[ 5.,  9., 10., 11.],
          [ 6.,  9., 10., 11.]],

         [[ 7., 12., 13., 14.],
          [ 8., 12., 13., 14.]]]])
Size of stacked z with dim=2: torch.Size([2, 2, 2, 4])
```

#### stack 함수대신 unsqueeze 함수와 cat 함수로 구현

In [47]:
print(f"x 텐서:\n{x}")
print(f"x 텐서:\n{x.size()}")
print(f"y 텐서:\n{y}")
print(f"y 텐서:\n{y.size()}")

x 텐서:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
x 텐서:
torch.Size([3, 3])
y 텐서:
tensor([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
y 텐서:
torch.Size([3, 3])


In [48]:
d= 0
#z = torch.stack([x,y],dim = d)
z = torch.cat([x.unsqueeze(d),y.unsqueeze(d)],dim=0)

print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


## 유용한 팁
- cat 함수나 stack 함수는 실전에서 매우 유용하게 활용될떄가 많음,
- 특히 여러이터레이션을 돌며 반복되는 작업을 수행한후 반복 작업의 결과물을 하나로 합쳐지는데 사용된다.
(아마 GPU로 여러 계산을 병렬로 실행후 하나의 결과값으로 만드는과정중에 사용되나봄)

In [49]:
result = []

for i in range(5):
    x = torch.FloatTensor(2,2)
    result += [x]
print(result)
    
result = torch.stack(result)

print(result)

[tensor([[1.5000e+01, 2.3694e-38],
        [2.3694e-38, 3.0000e+00]]), tensor([[1.4000e+01, 4.4766e+00],
        [2.3694e-38, 9.0000e+00]]), tensor([[1.3000e+01, 2.7812e+00],
        [2.3694e-38, 7.0000e+00]]), tensor([[-3.3006e+12,  1.4237e-42],
        [ 1.1000e+01,  1.2000e+01]]), tensor([[11.0000,  1.8750],
        [ 3.0000,  4.0000]])]
tensor([[[ 1.5000e+01,  2.3694e-38],
         [ 2.3694e-38,  3.0000e+00]],

        [[ 1.4000e+01,  4.4766e+00],
         [ 2.3694e-38,  9.0000e+00]],

        [[ 1.3000e+01,  2.7812e+00],
         [ 2.3694e-38,  7.0000e+00]],

        [[-3.3006e+12,  1.4237e-42],
         [ 1.1000e+01,  1.2000e+01]],

        [[ 1.1000e+01,  1.8750e+00],
         [ 3.0000e+00,  4.0000e+00]]])


# 유용한 함수들
## Expand 함수
- expand 함수는 차원의 크기가 1인 차원을 원하는 크기로 늘려주는 역활을 수행합니다. 
- 동일한 텐서를 그냥 반복하여 리스트에 넣고 cat함수를 해당차원에 대해 수행하는 것과 같다.

In [50]:
x = torch.FloatTensor([[[1,2]],
                       [[3,4]]])
print(x.size())


torch.Size([2, 1, 2])


In [51]:
y = x.expand(2,3,2)
print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


In [52]:
# 만약 cat 함수로 구현할시
y = torch.cat([x]*3,dim = 1)
print(y)
print(y.size())


tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


## Random Permutation 함수
- rabdperm함수는 랜덤 수열을 생성하는 파이토치 함수이다.
- 딥러닝은 랜덤성을 의존하는 부분이 많기 때문

In [53]:
x = torch.randperm(10)
print(x)
print(x.size())

tensor([2, 7, 8, 6, 0, 3, 9, 5, 4, 1])
torch.Size([10])


## Argument Max 함수
- argument 함수는 예를 들어설명하겠다
- 다음 수식에서 argument가 의미하는 것은 set X 에서 뽑을수있는 x값중 출력값을 최대로 만드는 입력을 반환하는 함수
- 즉 함수 f의 최대값이 아닌 f를 최대값으로 만드는 x를 반환하는 함수

In [54]:
x = torch.randperm(3**3).reshape(3,3,-1)
print(x)
print(x.size())


tensor([[[14,  9, 23],
         [22, 20,  4],
         [ 2, 17, 19]],

        [[11, 12,  8],
         [18, 25, 10],
         [ 6,  0, 21]],

        [[15, 13,  5],
         [16, 24,  1],
         [26,  3,  7]]])
torch.Size([3, 3, 3])


In [55]:
y = x.argmax(dim = 2)
print(y)
print(y.size())

tensor([[2, 0, 2],
        [1, 1, 2],
        [0, 1, 0]])
torch.Size([3, 3])


# Top-k 함수
- argmax의 상위 호환 버전임
- argmax 함수는 가장큰 한개의 값의 인덱스를 반환
- topk 함수는 가장 큰 k개의 값과 인덱스를 모두 반환

In [56]:
values, indice = torch.topk(x, k=1, dim = -1)
print(values.size())


torch.Size([3, 3, 1])


In [57]:
print(indice.size())    

torch.Size([3, 3, 1])


# Sort 함수
- 텐서 x를 원하는 차원 기준으로 정렬한 후 k개를 뽑는것 
- 즉, 결과물은 topk함수와 같다.

In [58]:
_, indice = torch.topk(x,k = 2,dim=-1)
print(indice.size())

torch.Size([3, 3, 2])


In [60]:
target_dim = -1
values, indice = torch.topk(x, k =x.size((target_dim)),largest=True)
print(values)

tensor([[[23, 14,  9],
         [22, 20,  4],
         [19, 17,  2]],

        [[12, 11,  8],
         [25, 18, 10],
         [21,  6,  0]],

        [[15, 13,  5],
         [24, 16,  1],
         [26,  7,  3]]])


# Masked File 함수
- 텐서내의 원하는 부분만 특정 값으로 바꿔치기 하는 함수이다.

In [61]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3,-1)
print(x)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])


In [62]:
print(x.size())

torch.Size([3, 3])


In [63]:
#논리 연산자를 통해 불리언 텐서를 만들어보자
mask = x > 4
print(mask)

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


In [64]:
# 이마스크를 통해서 mask_file 함수를 수행한다면 4보다 큰 값을 갖는 요소들을 특정 값으로 치완할수있게 됩니다.
# 다음 코드는 ㄱ보다 큰값을 모두 -1로 한번에 치환하도록 하는 코드입니다

y = x.masked_fill(mask,value=-1)
print(y)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])


# Ones & Zeros 함수
- 상수 값으로 텐서를 만들때 사용

In [65]:
print(torch.ones(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [66]:
print(torch.zeros(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [69]:
x = torch.FloatTensor([[1,2,3],
                       [4,5,6]])
print(x.size())

torch.Size([2, 3])


- 또는 ones_like와 zeros_like 함수를 통해서 특정 텐서와 같은 크기의 0또는 1 텐서를 만들수 있음 

In [70]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [71]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
