In [2]:
import torch

In [3]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       [[5,6],
                        [7,8]],
                       [[9,10],
                        [11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [4]:
print(x[0])
print(x[0,:])
print(x[0,:,:])

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]])


In [5]:
print(x[-1])
print(x[-1,:])
print(x[-1,:,:])

tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 9., 10.],
        [11., 12.]])


In [6]:
print(x[:,0,:])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


In [7]:
print(x[1:3,:,:].size())
print(x[:,:1,:].size())
print(x[:,:-1,:].size())

torch.Size([2, 2, 2])
torch.Size([3, 1, 2])
torch.Size([3, 1, 2])


In [16]:
x = torch.FloatTensor(115,4)

In [17]:
splits = x.split(4, dim=0)

for s in splits:
    print(s.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([3, 4])


In [18]:
x = torch.FloatTensor(100,4)


In [19]:
chunks = x.chunk(3,dim=0)

for c in chunks:
    print(c.size())

torch.Size([34, 4])
torch.Size([34, 4])
torch.Size([32, 4])


In [21]:
x = torch.FloatTensor([[[1,1],
                        [2,2]],
                       [[3,3],
                        [4,4]],
                       [[5,5],
                        [6,6]]])
indice = torch.LongTensor([2,1])
print(x.size())

torch.Size([3, 2, 2])


In [22]:
y = x.index_select(dim=0,index=indice)

print(y)
print(y.size())

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


In [23]:
x = torch.FloatTensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
y = torch.FloatTensor([[10,11,12],
                       [13,14,15],
                       [16,17,18]])
print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [24]:
z = torch.cat([x,y],dim=0)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])


In [25]:
z = torch.cat([x,y],dim=-1)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


In [26]:
z = torch.stack([x,y],dim=0)
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


In [27]:
z = torch.stack([x,y],dim=-1)
print(z)
print(z.size())

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])


In [28]:
#z = torch.stack([x,y])
z = torch.cat([x.unsqueeze(0),y.unsqueeze(0)],dim=0)
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])
